/* GENERATED by build_player.py — do not hand-edit.
   Frames detected from alpha; each sheet scaled by its own helmet width so
   the character never changes size between animations. ax/ay = foot anchor. */
window.SM = window.SM || {};
window.SM.PlayerAtlas = {
 "idle": [
  {
   "x": 0,
   "y": 0,
   "w": 65,
   "h": 125,
   "gw": 16.25,
   "gh": 31.25,
   "ax": 7.8,
   "ay": 31.25
  }
 ],
 "run": [
  {
   "x": 67,
   "y": 0,
   "w": 78,
   "h": 128,
   "gw": 19.5,
   "gh": 32.0,
   "ax": 8.57,
   "ay": 32.0
  },
  {
   "x": 147,
   "y": 0,
   "w": 69,
   "h": 123,
   "gw": 17.25,
   "gh": 30.75,
   "ax": 7.2,
   "ay": 30.75
  },
  {
   "x": 218,
   "y": 0,
   "w": 68,
   "h": 125,
   "gw": 17.0,
   "gh": 31.25,
   "ax": 7.17,
   "ay": 31.25
  },
  {
   "x": 288,
   "y": 0,
   "w": 72,
   "h": 127,
   "gw": 18.0,
   "gh": 31.75,
   "ax": 8.66,
   "ay": 31.75
  },
  {
   "x": 362,
   "y": 0,
   "w": 68,
   "h": 122,
   "gw": 17.0,
   "gh": 30.5,
   "ax": 7.81,
   "ay": 30.5
  },
  {
   "x": 432,
   "y": 0,
   "w": 68,
   "h": 129,
   "gw": 17.0,
   "gh": 32.25,
   "ax": 7.96,
   "ay": 32.25
  }
 ],
 "jump": [
  {
   "x": 502,
   "y": 0,
   "w": 73,
   "h": 127,
   "gw": 18.25,
   "gh": 31.75,
   "ax": 9.23,
   "ay": 31.75
  },
  {
   "x": 577,
   "y": 0,
   "w": 76,
   "h": 143,
   "gw": 19.0,
   "gh": 35.75,
   "ax": 9.22,
   "ay": 35.75
  },
  {
   "x": 655,
   "y": 0,
   "w": 71,
   "h": 120,
   "gw": 17.75,
   "gh": 30.0,
   "ax": 8.63,
   "ay": 30.0
  },
  {
   "x": 728,
   "y": 0,
   "w": 77,
   "h": 139,
   "gw": 19.25,
   "gh": 34.75,
   "ax": 12.03,
   "ay": 34.75
  }
 ],
 "hurt": [
  {
   "x": 807,
   "y": 0,
   "w": 79,
   "h": 125,
   "gw": 19.75,
   "gh": 31.25,
   "ax": 12.28,
   "ay": 31.25
  }
 ],
 "clear": [
  {
   "x": 888,
   "y": 0,
   "w": 81,
   "h": 125,
   "gw": 20.25,
   "gh": 31.25,
   "ax": 9.3,
   "ay": 31.25
  }
 ]
};
